### ISSUE TITLE
sql/tmall.sql中CREATE VIEW tmall_train_ub_action的代码写重了。

### ISSUE THREAD

**Issue by Libaier** [duckrun/odps_book#2]
tmall.sql中CREATE VIEW tmall_train_ub_action的代码写了两遍。
第二遍应该是
CREATE TABLE tmall_train_features as
SELECT
    t1.user_id,
    t1.brand_id,
    t1.buy_cnt,
    t1.click_d7,
    t1.collect_d7,
    t1.shopping_cart_d7,
    t1.click_d3,
    t1.collect_d3,
    t1.shopping_cart_d3
    t2.cvr
FROM tmall_train_ub_action t1
LEFT OUTER JOIN tmall_train_b_cvr t2
on t1.brand_id = t2.brand_id;

**Comment by duckrun** [comment]
thanks indeed. It is solved.
